# Practico 4 - JDBC - Ejercicio 1 (MySQL)
# Ajustar valores segun tu entorno local.

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3306/practico1a_mysql
db.user=root
db.password=

# En MySQL del practico 1.a la tabla esta en la base practico1a_mysql
# y no requiere prefijo de esquema.
db.table.cliente=cliente
