# Practico 4 - JDBC - Ejercicio 1 (PostgreSQL)
# Ajustar valores segun tu entorno local.

db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/postgres
db.user=postgres
db.password=root

# En PostgreSQL del practico 1.a se uso el esquema practico1a.
db.table.cliente=practico1a.cliente
