# Practico 4 - JDBC - Ejercicio 3 (Oracle XE)

db.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@//localhost:1521/XE
db.user=practico1c
db.password=practico1c

# En Oracle conviene filtrar por schema en mayusculas.
db.catalog=
db.schemaPattern=PRACTICO1C
db.tableNamePattern=%
db.table.types=TABLE
