# Practico 4 - JDBC - Ejercicio 3 (PostgreSQL)

db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://127.0.0.1:5432/postgres
db.user=postgres
db.password=

# Filtro de metadata para la base del ejercicio 1.c (PostgreSQL)
db.catalog=
db.schemaPattern=practico1c
db.tableNamePattern=%
db.table.types=TABLE
